trigger:
- main   # runs when code is pushed

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Run regression tests
- script: |
    npm test
  displayName: 'Run Regression Tests'